edition = "2021"
max_width = 100
# use_small_heuristics = "Max"
fn_single_line = true
trailing_comma = "Always"
reorder_imports = true
group_imports = "StdExternalCrate"
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
# normalize_comments = true
# wrap_comments = true
