/* ------------------------------------------------------------------------------------------------------------------ */
//! # mod: Coinbase Advance Trade Api
//!
//! This module contains the API for Coinbase Advance Trade.
/* ------------------------------------------------------------------------------------------------------------------ */
//! ### Modules
//! - allocate_portfolio
//! - cancel_orders
//! - cancel_pending_futures_sweep
//! - close_position
//! - commit_convert_trade
//! - create_convert_quote
//! - create_order
//! - create_portfolio
//! - delete_portfolio
//! - edit_order
//! - edit_order_preview
//! - edit_portfolio
//! - get_account
//! - get_api_key_permissions
//! - get_best_bid_ask
//! - get_convert_trade
//! - get_current_margin_window
//! - get_futures_balance_summary
//! - get_futures_position
//! - get_intraday_margin_setting
//! - get_market_trades
//! - get_order
//! - get_payment_method
//! - get_perpetuals_portfolio_summary
//! - get_perpetuals_position
//! - get_portfolio_breakdown
//! - get_portfolios_balances
//! - get_product
//! - get_product_book
//! - get_product_candles
//! - get_public_market_trades
//! - get_public_product
//! - get_public_product_book
//! - get_public_product_candles
//! - get_server_time
//! - get_transaction_summary
//! - list_accounts
//! - list_fills
//! - list_futures_positions
//! - list_futures_sweep
//! - list_orders
//! - list_payment_methods
//! - list_perpetuals_positions
//! - list_portfolios
//! - list_products
//! - list_public_products
//! - move_portfolio_funds
//! - opt_in_or_out_of_multi_asset_collateral
//! - preview_order
//! - schedule_futures_sweep
//! - set_intraday_margin_setting
/* ------------------------------------------------------------------------------------------------------------------ */

// Modules
pub mod allocate_portfolio;
pub mod cancel_orders;
pub mod cancel_pending_futures_sweep;
pub mod close_position;
pub mod commit_convert_trade;
pub mod create_convert_quote;
pub mod create_order;
pub mod create_portfolio;
pub mod delete_portfolio;
pub mod edit_order;
pub mod edit_order_preview;
pub mod edit_portfolio;
pub mod get_account;
pub mod get_api_key_permissions;
pub mod get_best_bid_ask;
pub mod get_convert_trade;
pub mod get_current_margin_window;
pub mod get_futures_balance_summary;
pub mod get_futures_position;
pub mod get_intraday_margin_setting;
pub mod get_market_trades;
pub mod get_order;
pub mod get_payment_method;
pub mod get_perpetuals_portfolio_summary;
pub mod get_perpetuals_position;
pub mod get_portfolio_breakdown;
pub mod get_portfolios_balances;
pub mod get_product;
pub mod get_product_book;
pub mod get_product_candles;
pub mod get_public_market_trades;
pub mod get_public_product;
pub mod get_public_product_book;
pub mod get_public_product_candles;
pub mod get_server_time;
pub mod get_transaction_summary;
pub mod list_accounts;
pub mod list_fills;
pub mod list_futures_positions;
pub mod list_futures_sweep;
pub mod list_orders;
pub mod list_payment_methods;
pub mod list_perpetuals_positions;
pub mod list_portfolios;
pub mod list_products;
pub mod list_public_products;
pub mod move_portfolio_funds;
pub mod opt_in_or_out_of_multi_asset_collateral;
pub mod preview_order;
pub mod schedule_futures_sweep;
pub mod set_intraday_margin_setting;
/* ------------------------------------------------------------------------------------------------------------------ */
